### ISSUE TITLE
Check that confidence calculation matches our latest discussions

### ISSUE THREAD

**Issue by hagenw** [audeering/audpsychometric#4]
@audeerington we had a long discussion for one of our databases what should be the best method to calculate confidence values for regression values. 

Could you check that the implementation provided in this package at https://github.com/audeering/audpsychometric/blob/master/audpsychometric/core/gold_standard.py#L30-L33
matches on what we had agreed on there.

/cc @sandneurodata

**Comment by hagenw** [comment]
Thanks for the detailed clarification.

This means at some point we should fix the current implementation and then at some point could use this package to calculate those values in the future.

**Comment by sandneurodata** [comment]
I can take care of fixing this in case
