### ISSUE TITLE
Return series instead of dataframes

### ISSUE THREAD

**Issue by hagenw** [audeering/audpsychometric#7]
In other packages we usually have functions that return a Series instead of a dataframe with several columns.
I'm referring to function like `gold_standard_mode` which return a dataframe containing the columns `gold_standard` and `confidence`.

I think it will be easier for a user if we would have instead two function, one returning the EWE as a Series, and other functions to calculate the confidence values. Then the user has also more flexibility to select the confidence calculation.

**Comment by hagenw** [comment]
@ChristianGeng any thoughts on this. Was there a particular reason you decided to dataframes instead of series?

**Comment by ChristianGeng** [comment]
Good to know that a series is the convention. This should be possible. 

Should this be done after resolving https://github.com/audeering/audpsychometric/pull/5? Or should this be started straight away?

**Comment by hagenw** [comment]
I would propose that we first finish #5. I will take over that pull request push the missing changes and will assign you as a reviewer.

Afterwards, you can then start tackling this issue, and thereafter we should be ready to make the first release.
